/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Me
         * @description The signed-in user, as seen by the API. Used to check the auth round trip.
         */
        get: operations["read_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/movies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Movies
         * @description The three films, in release order.
         */
        get: operations["list_movies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/species": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Species
         * @description Every dragon species in the catalog, by name.
         */
        get: operations["list_species"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/species/{species_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Species
         * @description One species with its film appearances, named dragons and sources.
         */
        get: operations["get_species"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/individuals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Individuals
         * @description Every named dragon in the catalog, by name.
         */
        get: operations["list_individuals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/individuals/{individual_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Individual
         * @description One named dragon with its species, film appearances, riders per film and sources.
         */
        get: operations["get_individual"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Species and named dragons whose name contains `q`, prefix matches first.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quiz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quiz
         * @description The active quiz: questions and options (no scores), options shuffled for this player.
         */
        get: operations["get_quiz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quiz/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Quiz Attempt
         * @description Score a finished quiz and save it. The encounter (next step) completes the attempt.
         */
        post: operations["create_quiz_attempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Appearance */
        Appearance: {
            /** Movie Id */
            movie_id: string;
            appearance_type: components["schemas"]["AppearanceType"];
            confidence: components["schemas"]["Confidence"];
            /** Evidence */
            evidence: string | null;
        };
        /**
         * AppearanceType
         * @enum {string}
         */
        AppearanceType: "featured" | "on_screen" | "background" | "mentioned" | "pictured";
        /** CharacterRef */
        CharacterRef: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * Confidence
         * @enum {string}
         */
        Confidence: "high" | "medium" | "low";
        /** CurrentUser */
        CurrentUser: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email?: string | null;
            /** Role */
            role: string;
        };
        /** DragonClass */
        DragonClass: {
            /** Value */
            value: string;
            /** @description `franchise` means the class comes from outside the films */
            scope: components["schemas"]["Scope"];
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** IndividualDetail */
        IndividualDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            species: components["schemas"]["SpeciesRef"];
            confidence: components["schemas"]["Confidence"];
            /**
             * Movies
             * @description Films the dragon appears in, in film order
             */
            movies: string[];
            /** Description */
            description: string | null;
            /** Notes */
            notes: string | null;
            /** Appearances */
            appearances: components["schemas"]["Appearance"][];
            /** Riders */
            riders: components["schemas"]["Rider"][];
            /** Sources */
            sources: components["schemas"]["Source"][];
        };
        /** IndividualRef */
        IndividualRef: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** IndividualSummary */
        IndividualSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            species: components["schemas"]["SpeciesRef"];
            confidence: components["schemas"]["Confidence"];
            /**
             * Movies
             * @description Films the dragon appears in, in film order
             */
            movies: string[];
        };
        /** Movie */
        Movie: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Year */
            year: number;
            /** Ordinal */
            ordinal: number;
        };
        /** Quiz */
        Quiz: {
            /**
             * Version
             * @example quiz_v1
             */
            version: string;
            /** Questions */
            questions: components["schemas"]["QuizQuestion"][];
        };
        /** QuizAttempt */
        QuizAttempt: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Quiz Version */
            quiz_version: string;
            /** Traits */
            traits: components["schemas"]["TraitScore"][];
        };
        /** QuizAttemptCreate */
        QuizAttemptCreate: {
            /**
             * Quiz Version
             * @example quiz_v1
             */
            quiz_version: string;
            /**
             * Answers
             * @description Chosen option id per question id; every question exactly once
             * @example {
             *       "q01_injured_dragon": "a"
             *     }
             */
            answers: {
                [key: string]: string;
            };
        };
        /** QuizOption */
        QuizOption: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** QuizQuestion */
        QuizQuestion: {
            /** Id */
            id: string;
            /** Prompt */
            prompt: string;
            /**
             * Options
             * @description In this player's shuffled order
             */
            options: components["schemas"]["QuizOption"][];
        };
        /** Rider */
        Rider: {
            /** Movie Id */
            movie_id: string;
            character: components["schemas"]["CharacterRef"];
            /**
             * Relation
             * @enum {string}
             */
            relation: "rider" | "owner" | "controller" | "companion";
            confidence: components["schemas"]["Confidence"];
        };
        /**
         * Scope
         * @enum {string}
         */
        Scope: "film" | "franchise";
        /** SearchResult */
        SearchResult: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "species" | "individual";
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** @description For individuals: their species */
            species: components["schemas"]["SpeciesRef"] | null;
        };
        /** Source */
        Source: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Type
             * @enum {string}
             */
            type: "film" | "official" | "book" | "wiki" | "other";
            /** Url */
            url: string | null;
            /** Accessed On */
            accessed_on: string | null;
        };
        /** SpeciesDetail */
        SpeciesDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            class: components["schemas"]["DragonClass"] | null;
            /** Size */
            size: ("tiny" | "small" | "medium" | "large" | "titan") | null;
            confidence: components["schemas"]["Confidence"];
            /**
             * Movies
             * @description Films the species appears in, in film order
             */
            movies: string[];
            /** Diet */
            diet: string | null;
            /** Description */
            description: string | null;
            /** Notes */
            notes: string | null;
            /** Appearances */
            appearances: components["schemas"]["Appearance"][];
            /**
             * Individuals
             * @description Named dragons of this species
             */
            individuals: components["schemas"]["IndividualRef"][];
            /** Sources */
            sources: components["schemas"]["Source"][];
        };
        /** SpeciesRef */
        SpeciesRef: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** SpeciesSummary */
        SpeciesSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            class: components["schemas"]["DragonClass"] | null;
            /** Size */
            size: ("tiny" | "small" | "medium" | "large" | "titan") | null;
            confidence: components["schemas"]["Confidence"];
            /**
             * Movies
             * @description Films the species appears in, in film order
             */
            movies: string[];
        };
        /** TraitScore */
        TraitScore: {
            /**
             * Id
             * @example courage
             */
            id: string;
            /**
             * Label
             * @example Courage
             */
            label: string;
            /**
             * Score
             * @description 0-100 within what this quiz allows
             */
            score: number;
            /**
             * Low
             * @description What a low score means
             */
            low: string;
            /**
             * High
             * @description What a high score means
             */
            high: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    read_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_movies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Movie"][];
                };
            };
        };
    };
    list_species: {
        parameters: {
            query?: {
                /** @description Only entries that appear in this film, e.g. `httyd2` */
                movie?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_species: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                species_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesDetail"];
                };
            };
            /** @description No entry with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_individuals: {
        parameters: {
            query?: {
                /** @description Only entries that appear in this film, e.g. `httyd2` */
                movie?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndividualSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_individual: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                individual_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndividualDetail"];
                };
            };
            /** @description No entry with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                /** @description Part of a name */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quiz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quiz"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_quiz_attempt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizAttemptCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizAttempt"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The quiz version is no longer the active one */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A question is unanswered, unknown or has an unknown option */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
