"""Build data/build/{seed.sql, dragons.json, dragons.csv} from the catalog (Plan.md §8.2).

Validates first and refuses to build a broken catalog. Output is deterministic (catalog row
order), so the build files only change when the catalog does.

Run from the repo root:  pnpm catalog:build
"""

import csv
import json
import sys
from datetime import date
from enum import Enum
from typing import cast

from catalog import (
    BUILD,
    FILES,
    MOVIE_IDS,
    Appearance,
    Character,
    Individual,
    RiderLink,
    Row,
    Species,
)
from validate_catalog import check, load

HEADER = "-- GENERATED by scripts/build_catalog.py from data/catalog/*.csv. Do not edit by hand.\n"

# Catalog file -> (table, {csv column: db column}). Insert order respects foreign keys.
TABLES = {
    "movies.csv": ("movies", {"movie_id": "id"}),
    "sources.csv": ("sources", {"source_id": "id"}),
    "species.csv": ("species", {"species_id": "id", "class_": "class"}),
    "individuals.csv": ("individuals", {"individual_id": "id"}),
    "characters.csv": ("characters", {"character_id": "id"}),
    "abilities.csv": ("abilities", {"ability_id": "id"}),
    "species_abilities.csv": ("species_abilities", {}),
    "appearances.csv": ("appearances", {}),
    "rider_links.csv": ("rider_links", {}),
}


def sql_literal(value: object) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, list):
        return (
            "array[" + ", ".join(sql_literal(v) for v in value) + "]::text[]" if value else "'{}'"
        )
    if isinstance(value, Enum):
        value = value.value
    if isinstance(value, date):
        value = value.isoformat()
    return "'" + str(value).replace("'", "''") + "'"


def seed_sql(tables: dict[str, list[Row]]) -> str:
    out = [HEADER, "begin;\n"]
    for file_name, (table, renames) in TABLES.items():
        rows = tables[file_name]
        if not rows:
            continue
        fields = list(FILES[file_name].model_fields)
        cols = ", ".join(renames.get(f, f) for f in fields)
        values = ",\n  ".join(
            "(" + ", ".join(sql_literal(getattr(r, f)) for f in fields) + ")" for r in rows
        )
        out.append(f"\ninsert into {table} ({cols}) values\n  {values};\n")
    out.append("\ncommit;\n")
    return "".join(out)


def dragons(tables: dict[str, list[Row]]) -> list[dict[str, object]]:
    species = cast(list[Species], tables["species.csv"])
    individuals = cast(list[Individual], tables["individuals.csv"])
    appearances = cast(list[Appearance], tables["appearances.csv"])
    riders = cast(list[RiderLink], tables["rider_links.csv"])
    characters = {c.character_id: c.name for c in cast(list[Character], tables["characters.csv"])}
    species_name = {s.species_id: s.name for s in species}

    def appears(kind: str, entity_id: str) -> list[dict[str, object]]:
        return [
            {"movie": a.movie_id, "type": a.appearance_type.value, "confidence": a.confidence.value}
            for a in appearances
            if a.entity_kind == kind and a.entity_id == entity_id
        ]

    entries: list[dict[str, object]] = []
    for s in species:
        entries.append(
            {
                "kind": "species",
                "id": s.species_id,
                "name": s.name,
                "class": {"value": s.class_, "scope": s.class_scope.value}
                if s.class_ and s.class_scope
                else None,
                "size": s.size,
                "diet": s.diet,
                "description": s.description,
                "appearances": appears("species", s.species_id),
                "known_individuals": [
                    i.individual_id for i in individuals if i.species_id == s.species_id
                ],
                "sources": s.source_ids,
                "confidence": s.confidence.value,
                "notes": s.notes,
            }
        )
    for i in individuals:
        entries.append(
            {
                "kind": "individual",
                "id": i.individual_id,
                "name": i.name,
                "species": {"id": i.species_id, "name": species_name[i.species_id]},
                "description": i.description,
                "appearances": appears("individual", i.individual_id),
                "riders": [
                    {
                        "movie": r.movie_id,
                        "character_id": r.character_id,
                        "character": characters[r.character_id],
                        "relation": r.relation,
                        "confidence": r.confidence.value,
                    }
                    for r in riders
                    if r.individual_id == i.individual_id
                ],
                "sources": i.source_ids,
                "confidence": i.confidence.value,
                "notes": i.notes,
            }
        )
    return entries


def write_flat_csv(entries: list[dict[str, object]]) -> None:
    cols = [
        "kind",
        "id",
        "name",
        "species",
        "class",
        "class_scope",
        "size",
        *MOVIE_IDS,
        "confidence",
        "sources",
        "description",
    ]
    with (BUILD / "dragons.csv").open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=cols, lineterminator="\n")
        writer.writeheader()
        for e in entries:
            cls = cast(dict[str, str] | None, e.get("class"))
            species = cast(dict[str, str] | None, e.get("species"))
            by_movie = {a["movie"]: a["type"] for a in cast(list[dict[str, str]], e["appearances"])}
            writer.writerow(
                {
                    "kind": e["kind"],
                    "id": e["id"],
                    "name": e["name"],
                    "species": species["name"] if species else e["name"],
                    "class": cls["value"] if cls else "",
                    "class_scope": cls["scope"] if cls else "",
                    "size": e.get("size") or "",
                    **{m: by_movie.get(m, "") for m in MOVIE_IDS},
                    "confidence": e["confidence"],
                    "sources": "|".join(cast(list[str], e["sources"])),
                    "description": e["description"],
                }
            )


def main() -> int:
    errors: list[str] = []
    tables = load(errors)
    if not errors:
        check(tables, errors)
    if errors:
        print(f"Not building: catalog has {len(errors)} problem(s). Run pnpm catalog:check.")
        return 1

    BUILD.mkdir(exist_ok=True)
    (BUILD / "seed.sql").write_text(seed_sql(tables), encoding="utf-8", newline="\n")
    entries = dragons(tables)
    (BUILD / "dragons.json").write_text(
        json.dumps(entries, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n"
    )
    write_flat_csv(entries)
    kinds = [e["kind"] for e in entries]
    print(
        f"Built data/build/: seed.sql, dragons.json and dragons.csv "
        f"({kinds.count('species')} species, {kinds.count('individual')} individuals)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
